version: "3.8"

services:
  cpp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp-dev-container
    volumes:
      - .:/workspace   # mount current repo
    shm_size: '512m'
    tty: true
    stdin_open: true
